version = 0.1

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "kp-core-prod"
region = "us-west-2"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "kp-core-dev"
region = "us-west-2"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true