AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  kind-presence

  Sample SAM Template for kind-presence

Parameters:
  OwnerName:
    Type: String
    Default: KatherineLorenzo
    Description: Hi, nice to meet you!

  ProjectName:
    Type: String
    Default: kind-presence
    Description: be always kind to others

  Environment:
    Type: String
    Default: dev
    Description: environment to deploy

Resources:
  KPYogaPosesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub kp-yoga-poses-${Environment}
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Owner
          Value: !Ref OwnerName
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  KPDocumentsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub kp-documents-${Environment}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Owner
          Value: !Ref OwnerName
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  KPYogaPosesTable:
    Value: !Ref KPYogaPosesTable
  KPDocumentsBucket:
    Value: !Ref KPDocumentsBucket
